export const dataThietBi = [
  {
    id: 1,
    name: "Cáp chuyển từ Cổng USB sang PS2...",
    countStar: 4,
    countTest: 15,
    price: "69.900 đ",
    discord: "-39%",
    image: require("../assets/1b.png"),
  },
  {
    id: 2,
    name: "Cáp chuyển từ Cổng USB sang PS2...",
    countStar: 4,
    countTest: 15,
    price: "69.900 đ",
    discord: "-39%",
    image: require("../assets/2b.png"),
  },
  {
    id: 3,
    name: "Cáp chuyển từ Cổng USB sang PS2...",
    countStar: 4,
    countTest: 15,
    price: "69.900 đ",
    discord: "-39%",
    image: require("../assets/3b.png"),
  },
  {
    id: 4,
    name: "Cáp chuyển từ Cổng USB sang PS2...",
    countStar: 4,
    countTest: 15,
    price: "69.900 đ",
    discord: "-39%",
    image: require("../assets/4b.png"),
  },
  {
    id: 5,
    name: "Cáp chuyển từ Cổng USB sang PS2...",
    countStar: 4,
    countTest: 15,
    price: "69.900 đ",
    discord: "-39%",
    image: require("../assets/5b.png"),
  },
  {
    id: 6,
    name: "Cáp chuyển từ Cổng USB sang PS2...",
    countStar: 4,
    countTest: 15,
    price: "69.900 đ",
    discord: "-39%",
    image: require("../assets/6b.png"),
  },
];
